name: Deploy API

on:
  push:
    branches:
      - main  # You can specify the branch that will trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run your API or tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use the secret
        run: |
          node your-api-file.js  # Example of running your Node.js script that uses the API key
